# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: "mysql:8.0.26"
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=sail
            - MYSQL_USER=sail
            - MYSQL_PASSWORD=sail
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        volumes:
            - ./.docker/mysql/conf.d:/etc/mysql/conf.d
            - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./.docker/storage/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - sail
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 2048M
    phpmyadmin:
        container_name: sail_phpmyadmin
        image: "phpmyadmin/phpmyadmin:latest"
        restart: unless-stopped
        environment:
            - "PMA_ARBITRARY=1"
            - "PMA_HOST=mysql"
            - "PMA_USER=root"
            - "PMA_PASSWORD=root"
            - "PHP_UPLOAD_MAX_FILESIZE=50G"
            - "PHP_MAX_INPUT_VARS=50000"
            - "MAX_EXECUTION_TIME=600"
            - "MEMORY_LIMIT=256M"
        ports:
            - "8080:80"
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            - sail
        deploy:
            resources:
                limits:
                    cpus: "0.25"
                    memory: 256M
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
